[general]
listen_ip = "0.0.0.0"
listen_port = 80
# if under reverse proxy
#public_url = "https://storage.example.com"
#public_port = 443
public_url = "http://localhost:8080"
public_port = 80

[backends.local]
path = "/var/tmp/test"

[auth]
enable_registration = true
oidc_enabled = true
# Where the .well-known/openid-configuration exists
oidc_issuer_url = "https://accounts.example.com"
oidc_client_id = ""
oidc_client_secret = ""
oidc_claims = []
# Should an account be created if SSO user id doesn't exist already
oidc_create_account = true

[smtp]
# TODO: 
